import { FC } from 'react';
import { Toolbar, Box } from '@mui/material';

import { Navbar, Sidebar } from '../ui';
import Head from 'next/head';

const sidebarWidth = 250;

interface Props {
    children: React.ReactNode;
    title?: string;
}

export const MainLayout: FC<Props> = ({ title= 'Try Hard', children }) => {
  return (
    <Box 
    className="animate__animated animate__fadeIn animate__faster"
    sx={{ display: 'flex', }}>

    <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

      <Navbar sidebarWidth={ sidebarWidth } />
      <Sidebar sidebarWidth={ sidebarWidth } />

      <Box 
          component='main'
          sx={{ flexGrow: 1, p: 3}}
      >
        <Toolbar />

        {children}

      </Box>

    </Box>
  )
}





