import { FC } from 'react';
import { Toolbar, Box } from '@mui/material';

import { Navbar, Sidebar } from '../ui';
import Head from 'next/head';

const sidebarWidth = 250;

interface Props {
    children: React.ReactNode;
    title?: string;
}

export const MainLayout: FC<Props> = ({ title= 'Try Hard', children }) => {
  return (
    <Box 
    className="animate__animated animate__fadeIn animate__faster"
    sx={{ display: 'flex', }}>

    <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
/>
    </Head>

      <Navbar sidebarWidth={ sidebarWidth } />
      <Sidebar sidebarWidth={ sidebarWidth } />

      <Box 
          component='main'
          sx={{ flexGrow: 1, p: 3}}
      >
        <Toolbar />

        {children}

      </Box>

    </Box>
  )
}





